### ISSUE TITLE
[user]Nifty: Java backend error 

### ISSUE THREAD

**Issue by Shojigo** [WOVNio/wovnjava#28]
忘れない為のmemo:

本日、開発環境にリリースしたところ、以下のエラーが発生いたしました。

------------------------------------------------------------------------
この状態でアクセスを行ったところ、下記のようなエラーが出力されました。
2016/04/28 16:40:56 org.apache.catalina.core.StandardContext filterStart
致命的: フィルタ wovn の起動中の例外です
java.lang.ClassNotFoundException: com.github.wovnio.wovnjava.WovnServletFilter
at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1713)
at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1558)
at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:527)
at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:509)
at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:137)
at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:107)
at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4746)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5399)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
at java.lang.Thread.run(Thread.java:662)
------------------------------------------------------------------------

web.xmlについては、指示いただいたサイトにあったものを、そのままコピーしております。
# コメントにあった「ユーザートークン」「シークレットキー」等は、変更しております。

弊社環境は、
------------------------------------------------------------------------
$ java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)
------------------------------------------------------------------------
となっているとのこと、情報を基盤担当から頂きましたが、
Mavenでのビルドでは、1.8で行っているため、この辺が原因かと思っております。
GW明けになってしまいますが、再度、1.6.45の環境で、wovnを再ビルドして検証してみたいと思います。
もし、他に原因等があるようでしたら、ご教示頂けると幸いです
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

先週お送りしたメールの問題については解決いたしました。
一応原因は、Eclipse&Mavenを使用してJarをビルドしていたのですが、
Githubから、ソースが取得できておらず、Classファイルの無いJarファイルが出来上がっておりました。

Mavenの設定を見直しましたが、Githubからソース取得ができないため手動でソースファイルを取得＆設置し、
JDK1.6.45でビルドできるようになりました。
※pom.xmlも、ライブラリ関連が足りていないため、Githubにあるものを流用しております。

結果、ビルドの結果として、
　wovnjava-0.0.1.jar
　wovnjava-0.0.1-jar-with-dependencies.jar
の2ファイルが生成されております。

弊社サーバでは不足しているライブラリがあるようですので、wovnjava-0.0.1-jar-with-dependencies.jar を
使用したところ、無事にTomcatの起動時にエラーは出なくなりました。
------

続いて以下の手順を行いましたが、今のところ翻訳されたページを見ることが出来ておりません。
チェックすべき項目等がございましたら、ご教示いただきたく。

前提
 Web.xmlの追記内容
---------------------------------------------------------------------------------
        
        <filter>
          <filter-name>wovn</filter-name>
          <filter-class>com.github.wovnio.wovnjava.WovnServletFilter</filter-class>
          <init-param>
            <param-name>userToken</param-name>
            <param-value>8PIPh</param-value>
          </init-param>
          <init-param>
            <param-name>secretKey</param-name>
            <param-value>571f122470b317711d0001bb</param-value>
          </init-param>
          <init-param>
            <param-name>urlPattern</param-name>
            <param-value>query</param-value>
          </init-param>
          <init-param>
            <param-name>query</param-name>
            <param-value>wovn</param-value>
          </init-param>
          <init-param>
            <param-name>defaultLang</param-name>
            <param-value>ja</param-value>
          </init-param>
        </filter>
        
-----------------Filter Mapping の設定の最上位に、以下を追記 --------------------
        
        <filter-mapping>
          <filter-name>wovn</filter-name>
          <url-pattern>/yokohama-onsen/*</url-pattern>
        </filter-mapping>
        
---------------------------------------------------------------------------------

０．Web.xmlを配置して、Tomcatを再起動
１．Wovn.io にログイン
２．DashBoardから、下記URLの翻訳を登録（Publishも実施）

　http://check.onsen2.pre-cms.nifty.com:8080/yokohama-onsen/onsen006590/
　http://check.onsen2.pre-cms.nifty.com:8080/yokohama-onsen/onsen008577/

３．上記URLのままで、正常（日本語)に表示されることを確認→OK

４．以下のURLで、英語に翻訳されることを確認→NG
　※３と内容が変わらず。
　http://check.onsen2.pre-cms.nifty.com:8080/yokohama-onsen/onsen006590/?wovn=en
　http://check.onsen2.pre-cms.nifty.com:8080/yokohama-onsen/onsen008577/?wovn=en

※４のアクセス時に、サーバ上のログには、何も出ていない

という状況になっております。
御社側のサーバに、弊社からのアクセスログ等があればご確認頂けないでしょうか。
また、Filter動作時に弊社側サーバへログ出力する方法がありましたら、
合わせてご教示頂けると助かります。

**Comment by miniuchi** [comment]
Issue moved to [WOVNio/equalizer #709](https://github.com/WOVNio/equalizer/issues/709) via [**ZenHub.io**](https://www.zenhub.io/)
